### ISSUE TITLE
🐛 [BUG]: Updating edge jumps to top handle 

### ISSUE THREAD

**Issue by Zambiorix** [bcakmakoglu/vue-flow#1647]
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

I have custom node with 4 source handles all around.

```
<Handle id="source-left" type="source" :position="Position.Left" />
<Handle id="source-top" type="source" :position="Position.Top" />
<Handle id="source-right" type="source" :position="Position.Right" />
<Handle id="source-bottom" type="source" :position="Position.Bottom" />
```

Add 2 custom nodes in flow called A and B
Connect an edge between (source) B-left and (target) A-left
Try updating the edge source from B-left to B-bottom.

As soon as you move the handle, the edge target jumps from A-left to A-top
So, when updating the source to another handle, the target's handle always jumps to top (temporarily).

### Expected Behavior

Target handle should stay connected

### Steps To Reproduce

https://codesandbox.io/p/devbox/adoring-violet-tzvkh7

### Anything else?

See screenshots below

**Comment by Zambiorix** [comment]
![A](https://github.com/user-attachments/assets/50964436-1cd9-44ba-a523-48e7d3cd4a4f)
![A](https://github.com/user-attachments/assets/b7b8a8b0-12b4-4661-8c28-9fd064133565)

**Comment by Zambiorix** [comment]
![A](https://github.com/user-attachments/assets/6f5cab05-35c9-435f-89cc-e78815afcac4)

![B](https://github.com/user-attachments/assets/4bc7431b-abb2-45a9-a90f-5b51482c2ad4)

**Comment by bcakmakoglu** [comment]
Please provide a proper reproduction of the issue.

You can find a sandbox template here: https://codesandbox.io/p/devbox/vue-flow-basic-gfgro4

I’ll gladly check what’s wrong once I’m back from my vacation once you’ve provided a repro ^^

**Comment by Zambiorix** [comment]
Ok, thanks, I'll provide a reproduction today

**Comment by Zambiorix** [comment]
Here is a link to a reproduction:

https://codesandbox.io/p/devbox/adoring-violet-tzvkh7

Just drag the edge from node B and you'll see side A jumping from left to top.

**Comment by bcakmakoglu** [comment]
Will be fixed in the next release

**Comment by bcakmakoglu** [comment]
Fixed with 1.41.3

**Comment by yiwwhl** [comment]
> Fixed with 1.41.3

@bcakmakoglu Thank you very much for your efforts; however, I am still encountering an issue. Whenever I call addNodes or directly add new nodes and edges data, all the old node handles move to the top and bottom, which is quite confusing for me. Have you ever come across a similar problem?

https://github.com/user-attachments/assets/e8c3b001-af05-4047-89f4-83a38214c463

**Comment by bcakmakoglu** [comment]
A reproduction for that issue would be needed for me to debug it, just a video isn't telling me much about your code and what might be happening.

**Comment by yiwwhl** [comment]
> A reproduction for that issue would be needed for me to debug it, just a video isn't telling me much about your code and what might be happening.

I'm sorry, I just saw this. Here is the reproduction logic I wrote for the issue:
https://stackblitz.com/edit/vitejs-vite-zk61qe?file=src%2FuseLayout.ts

**Comment by bcakmakoglu** [comment]
That's a bit too complex for a simple repro tbh, I can't figure out where you do what in that sandbox and it'd take me too much time to sit down and analyse everything in there 😅

Can you strip it down to as little as possible that still re-creates the issue.
